services:
  stats-server:
    build: ./stats/server
    network_mode: host
    environment:
      - SERVER_PORT=9090

  stats-db:
    image: postgres:16.1
    ports:
      - "6543:5432"
    volumes:
      - ./volumes/stats-postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stats_db
      - POSTGRES_USER=stats_user
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build: ./ewm_main_service
    network_mode: host

  ewm-db:
    image: postgres:16.1
    ports:
      - "6544:5432"
    volumes:
      - ./volumes/ewm-postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ewm_db
      - POSTGRES_USER=main_user
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10