server:
  port: 8080

stats:
  client:
    url: http://stats-server:9090

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always
      platform: postgresql
      data-locations: classpath:schema.sql

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ewm-db:5433/ewm_db
    username: main_user
    password: 12345

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm.jdbc.bind: TRACE
      springframework:
        orm:
          jpa: INFO
          jpa.JpaTransactionManager: DEBUG
        transaction: INFO
        boot:
          context:
            config: DEBUG
