CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(254) NOT NULL,
    email VARCHAR(250) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS events(
    id BIGSERIAL PRIMARY KEY,
    created_on TIMESTAMP WITHOUT TIME ZONE,

    initiator_id BIGINT NOT NULL,
    category_id INTEGER NOT NULL,

    title VARCHAR(120) NOT NULL,
    annotation VARCHAR(2000) NOT NULL,
    description VARCHAR(7000) NOT NULL,

    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    paid BOOLEAN NOT NULL,
    participant_limit INTEGER DEFAULT 0,

    published_on TIMESTAMP WITHOUT TIME ZONE,

    request_moderation BOOLEAN DEFAULT FALSE,
    confirmed_requests INTEGER DEFAULT 0,

    state VARCHAR(50) NOT NULL,
    views INTEGER NOT NULL,

    location_lat DOUBLE PRECISION NOT NULL,
    location_lon DOUBLE PRECISION NOT NULL,

    CONSTRAINT fk_event_initiator
    FOREIGN KEY (initiator_id)
    REFERENCES users (id),

    CONSTRAINT fk_event_category
    FOREIGN KEY (category_id)
    REFERENCES categories (id)
);

CREATE TABLE IF NOT EXISTS requests(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_event_id FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT unique_user_event UNIQUE (user_id, event_id)
    );

